# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-28c172d0-1b47-47cd-b075-2ff43a880e65";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-28c172d0-1b47-47cd-b075-2ff43a880e65".device = "/dev/disk/by-uuid/28c172d0-1b47-47cd-b075-2ff43a880e65";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/10CD-FAFC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a83d6c13-43c6-4be2-ae4d-12f24f3e4530"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
